### ISSUE TITLE
userConfig-example.js in Readme.md is obsolete

### ISSUE THREAD

**Issue by lcb931023** [whatwedo/gulp-wp-theme#11]
Can't find userConfig-example.js in gulp. From the commit histories it looks like something refactored into config.js? Needs an update in Readme

**Comment by renestalder** [comment]
You're right. Merged changes from different repositories and didn't update all the parts of the code or readme.

Alternatively you can take a look at non WordPress repository, which have a development and production config and merge process in the main config. Same mechanism and you can copy one of the two configs and make your own environment configuration with config-user.js.
https://github.com/whatwedo/gulp-boilerplate/tree/master/gulp

I will update this repository asap to reflect this changes.

**Comment by lcb931023** [comment]
Thanks man! Very useful boilerplate.

**Comment by renestalder** [comment]
The missing configs are in the repository now. Please notice, they have different names as described before in the readme. They nearly identical to our other, non-wordpress boilerplate.
