### ISSUE TITLE
Cannot find module package.json

### ISSUE THREAD

**Issue by raidenz** [whatwedo/gulp-wp-theme#47]
i dont know this is error because my version or not, i use
node v4.2.1
npm 3.5.4

i use cygwin to test it
i have problem to start the script 
Error: Cannot find module '/cygdrive/g/gulp/gulp-wp-theme/package.json'

i solve this by change var packageConfig = require(process.env.PWD + '/package.json');
to var packageConfig = require('../package.json');

in gulp config-development and config-production

i have question why not change it to
var packageConfig = require('../package.json');
i think its save for other operating system

**Comment by renestalder** [comment]
What's your project's file structure? Did you install the package via npm or manually downloading it? Do you have a package.json in your projects root folder?

`packageConfig = require(process.env.PWD + '/package.json');` ensures that it uses your config and not the config of the gulp-wp-theme package. With your change, this gets useless.

So first ensure you have a package config in the project's root and then check you are running the command out of the root folder.

**Comment by raidenz** [comment]
yes thanks, im doing it wrong. i manually download it.
now i install it from npm and its work
thanks :+1:

**Comment by renestalder** [comment]
Good to hear. Let us know if you have troubles.
