### ISSUE TITLE
Error: Cannot find module 'gulp-ruby-sass'

### ISSUE THREAD

**Issue by chuckmo** [whatwedo/gulp-wp-theme#8]
Looks like it has to be installed globally after all. No mention of that in the README

**Comment by renestalder** [comment]
@chuckmo Nope sorry, it's a bug. I removed the initial Sass setup in favour of Stylus as default, which means, the Sass package is not included, but the tasks still reference to it, even they are not used. You can remove the `styles/sass.js` file and it should run or you can add the missing package to the package.json.

I will fix it in the repository.
